#!/bin/sh
HOMEDIR=/home/espruino
PROJECTDIR=${PWD}
ESPRUINO=Edge
BOARD=ESP32
ESPIDF=V3

. ./testVar.sh
ESPRUINODIR=$HOMEDIR/Espruino/Espruino$ESPRUINO
ESPIDF=$HOMEDIR/tools/ESP32$ESPIDF

export ESP_IDF_PATH=$ESPIDF/esp-idf 
export ESP_APP_TEMPLATE_PATH=$ESPIDF/app 
export PATH=$PATH:$ESPIDF/xtensa-esp32-elf/bin/

UNSUPPORTED=$PROJECTDIR/files$BOARD
cd $ESPRUINODIR
make clean 
RELEASE=1 UNSUPPORTEDMAKE=$UNSUPPORTED BOARD=$BOARD make >$PROJECTDIR/log/$BOARD/stdout 2>$PROJECTDIR/log/$BOARD/stderr
RELEASE=1 UNSUPPORTEDMAKE=$UNSUPPORTED BOARD=$BOARD make wrappersources >$PROJECTDIR/log/$BOARD/wrapperout 2>$PROJECTDIR/log/$BOARD/wrappererr
cd $PROJECTDIR
mv $ESPRUINODIR/*esp32* ./firmware/$BOARD
